# - * -coding: utf - 8 - * -
	""
"PW2 Tarea05Mis programas.ipynb

Automatically generated by Colaboratory.

Original file is located at
https: //colab.research.google.com/drive/1qTsAnzV3rApuXyvnxB1qVRVcJ8BKUbYY
	""
"

nombre = 'Hugo'
apellido = ' Fernandez '
print("Mi nombre es " + nombre + apellido)

print("Cual es tu nombre")
miNombre = input()
print("Tu nombre es " + miNombre)

n1 = float(input("Introduce el número uno: "))
n2 = float(input("Introduce el numero dos: "))
suma = n1 + n2
print("La suma es: ", suma)

import random
adivina_numero = random.randint(1, 10)
resp_usuario = int(input("Adivina el número del 1 al 10: "))
if adivina_numero > resp_usuario:
	print("¡Tu estimación es muy baja!")
elif adivina_numero < resp_usuario:
	print("Tu estimado es muy alto!")
else :
	print("¡Felicidades, adivinaste el número !")
print("El número es", adivina_numero)

#AND
#OR
#NOT



print("Operadores Logicos")
print("AND")
#And Multiplicacion logica
print(True and True) #1*1 = 1
print(True and False) #1*0 = 0
print(False and True) #0*1 = 0
print(False and False) #0*0 = 0

print("OR")
#Or Suma logica
print(True or True) #1+1 = > 1
print(True and False) #1+0 = 1
print(False and True) #0+1 = 1
print(False and False) #0+0 = 0
print("Not")
#Not Negacion
print(not(True)) #resultado: False
print(not(False)) #resultado: True



print("\n------------------------")
#ejercicio operadores logicos
a = 10
b = 15
c = 20

resultado = ((a < b) and(b < c))
print(resultado)